sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t hernandezmdev/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true hernandezmdev/docker-react npm run test